

register:
    path: /register
    controller: App\Controller\RegisterController\RegisterController::index

register_complete:
    path: /register/complete
    controller: App\Controller\RegisterController::complete
