

# register:
#     path: /register
#     controller: App\Controller\AuthController::index

# register_complete:
#     path: /register/complete
#     controller: App\Controller\RegisterController::complete
